# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-spice" do
  name "jj-spice"
  desc "Stacked change requests for Jujutsu VCS"
  homepage "https://github.com/alejoborbo/jj-spice"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-spice"

  on_macos do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_amd64.tar.gz"
      sha256 "079f0c76bd1dd07d2c8a668d8a4d78bacf32e2593122999d29675070a767a4b8"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_arm64.tar.gz"
      sha256 "f06b5b7e0c49ee24fd24f2eed16765544f0dfd3e09adac8c4f7da3410e7aa777"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_amd64.tar.gz"
      sha256 "b8291301824caa02df5b53db873a6f6fe87a2b923961fc5d0b4a2580d599cdb8"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_arm64.tar.gz"
      sha256 "3fc3001c6d3f07f2825ae214f539972b49efa465254abaa9ab1ca36f6a57ed5b"
    end
  end

  # No zap stanza required
end
