# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-spice" do
  name "jj-spice"
  desc "Stacked change requests for Jujutsu VCS"
  homepage "https://github.com/alejoborbo/jj-spice"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-spice"

  on_macos do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_amd64.tar.gz"
      sha256 "31e2e7a4623d198ee4a70bc14b71b71fffd35da2cece5e3207f54e0f41bc6f7f"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_arm64.tar.gz"
      sha256 "a96bf1439a9607ab672c653c91508c0fc8fbe61030a1d101d903cc66ade8d232"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_amd64.tar.gz"
      sha256 "f8010c8eb004f3f4feb0bffe7f7b267d2e2e0801f78290258dd97b5dacb6c1d7"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_arm64.tar.gz"
      sha256 "c10156bb0ccf085c1e36dd89d457ace50669235e546458dcbe0b1c363683731c"
    end
  end

  # No zap stanza required
end
