# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-spice" do
  name "jj-spice"
  desc "Stacked change requests for Jujutsu VCS"
  homepage "https://github.com/alejoborbo/jj-spice"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-spice"

  on_macos do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_amd64.tar.gz"
      sha256 "42330009c50d8f4ff4636aee736071f1b81172b9f5de3682af71f07a97dfd2f5"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_darwin_arm64.tar.gz"
      sha256 "d3497b16e9a94a0770b3e64275b0bc0929a3569d880c6293bf5fd121114c6d84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_amd64.tar.gz"
      sha256 "e5cc02ebc39d2293584c1e7147ad48ab28dd8b41bda8238abfc6806b6cf578b4"
    end
    on_arm do
      url "https://github.com/alejoborbo/jj-spice/releases/download/v#{version}/jj-spice_#{version}_linux_arm64.tar.gz"
      sha256 "083147ad8cf917c0f16c967b49238066fc841c3bc9e5e3762f2c0e45f4d2c6f5"
    end
  end

  # No zap stanza required
end
